version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "ember",
    "react"
  ]
  environment = [
    "browser",
    "jquery"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"